apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: swiftpay
spec:
  replicas: 1
  selector:
    matchLabels: {app: postgres}
  template:
    metadata:
      labels: {app: postgres}
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports: [{containerPort: 5432}]
          env:
            - {name: POSTGRES_USER,     value: swiftpay}
            - {name: POSTGRES_PASSWORD, value: swiftpay_secret}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec: {command: [pg_isready, -U, swiftpay]}
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim: {claimName: postgres-pvc}
        - name: init-script
          configMap: {name: postgres-init}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: swiftpay
spec:
  selector: {app: postgres}
  ports: [{port: 5432, targetPort: 5432}]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: swiftpay
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests: {storage: 5Gi}
